let currentSchemes=null;
const schemePurpose={formed_label:'Обозначение образуемого участка',public_use_context:'Раздел общего пользования — по тексту',unknown:'Назначение не определено'};
function jointSchemePreview(d){
 const accepted=d.tables.map((t,i)=>({...t,reviewIndex:i})).filter(t=>t.state==='review_required'&&t.outline_xy),rings=d.review.union_rings_xy||[];
 if(!accepted.length)return '';
 function draw(ts,rs,name){
  const pts=ts.flatMap(t=>t.outline_xy),xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]),x=Math.min(...xs),y=Math.min(...ys),dx=Math.max(...xs)-x,dy=Math.max(...ys)-y,scale=620/Math.max(dx,dy,1),h=Math.max(180,dy*scale+92),ox=(700-dx*scale)/2,oy=46;
  const path=r=>'M'+r.map(p=>`${ox+(p[0]-x)*scale},${h-oy-(p[1]-y)*scale}`).join(' L')+' Z';
  return `<svg viewBox="0 0 700 ${h}" style="width:700px;max-width:100%;background:#f2f5ef" role="img" aria-label="${escapeHtml(name)}"><text x="12" y="22">Y ↑ · X → · исходные столбцы таблиц</text>${ts.map(t=>`<path d="${path(t.outline_xy)}" fill="${t.purpose_hint==='public_use_context'?'#b7d4b7':'#f0d09b'}" stroke="#657368" stroke-width="1.5"><title>${escapeHtml(t.label)}</title></path>`).join('')}${rs.map(r=>`<path d="${[r.exterior_xy,...r.holes_xy].map(path).join(' ')}" fill="none" stroke="#315c46" stroke-width="2.5" fill-rule="evenodd"/>`).join('')}${ts.map(t=>{const xx=t.outline_xy.map(p=>p[0]),yy=t.outline_xy.map(p=>p[1]),cx=(Math.min(...xx)+Math.max(...xx))/2,cy=(Math.min(...yy)+Math.max(...yy))/2;return `<text x="${ox+(cx-x)*scale}" y="${h-oy-(cy-y)*scale}" font-size="11" text-anchor="middle">${t.reviewIndex+1}</text>`}).join('')}<text x="12" y="${h-12}">Контур проекта в X/Y · геопривязка не подтверждена</text></svg>`;
 }
 return draw(accepted,rings,'Все принятые для сверки таблицы проекта в общем X/Y')+'<p>Зелёный — контекст общего пользования; охра — остальные обозначения. Подписи: '+accepted.map(t=>(t.reviewIndex+1)+' — '+escapeHtml(t.label)).join('; ')+'.</p>'+ (rings.length>1?rings.map((r,i)=>{const ts=accepted.filter(t=>(r.table_indices||[]).includes(t.reviewIndex));return ts.length?`<details><summary>Часть ${i+1} крупнее · таблиц: ${ts.length}</summary><p>Масштаб этой части отдельный; положение относительно других частей показано на общем рисунке выше.</p>${draw(ts,[r],'Часть '+(i+1)+' проекта крупнее в X/Y')}</details>`:''}).join(''):'');
}
function jointSchemeReview(d){
 const r=d.review;if(!r||!d.tables?.length)return '';
 const n=x=>x==null?'не рассчитано':Number(x).toLocaleString('ru-RU',{maximumFractionDigits:6});
 return `<details><summary>Совместная проверка таблиц проекта</summary><p>${escapeHtml(r.warning)}</p><p>Таблиц для сверки: ${r.accepted_count}; исключено: ${r.excluded_count}. Общий контур: ${r.component_count} частей.<br>Сумма площадей: ${n(r.sum_area_m2)} м²; площадь объединения: ${n(r.union_area_m2)} м²; наложения: ${n(r.overlap_area_m2)} м².</p>${r.role_totals.map(x=>`<p>${schemePurpose[x.purpose_hint]||'Назначение не определено'}: ${x.count} таблиц, сумма ${n(x.sum_area_m2)} м².</p>`).join('')}${r.origin_statements.map(x=>`<p>Исходный участок по тексту: <b>${escapeHtml(x.cadastral_number)}</b>; указано ${n(x.stated_area_m2)} м² · стр. ${x.page}.<br>${escapeHtml(x.source_excerpt)}</p>`).join('')}${r.division_statements.length?`<p><b>В тексте найдено образование путём раздела существующего участка.</b> Номера: ${escapeHtml([...new Set(r.division_statements.map(x=>x.cadastral_number))].join('; '))}; страницы: ${escapeHtml([...new Set(r.division_statements.map(x=>x.page))].join(', '))}. Обозначения :ЗУ не объявляются свободной землёй.</p>`:''}${r.area_comparisons.map(x=>`<p>Сопоставление всех таблиц с площадью ${escapeHtml(x.cadastral_number)}: разница ${n(x.difference_m2)} м². Применимость такого объединения к исходному участку требует сверки; совпадение площади не подтверждает полноту или актуальную границу.</p>`).join('')}${r.origin_ambiguous?'<p>Указания исходного участка/площади неоднозначны; общая площадь с ними автоматически не сопоставляется.</p>':''}${r.quarter_statements.length?'<p>Кварталы, прямо указанные в тексте: '+r.quarter_statements.map(x=>escapeHtml(x.cadastral_quarter)+' (стр. '+x.page+')').join('; ')+'.</p>':''}${r.quarter_disagreement?'<p><b>Квартал исходного номера не совпадает с прямыми указаниями квартала в тексте. Требуется сверка документа.</b></p>':''}${r.overlap_pair_count?'<p>Пар с площадным пересечением: '+r.overlap_pair_count+'. '+r.overlap_pairs.map(x=>escapeHtml(x.left)+' / '+escapeHtml(x.right)+': '+n(x.area_m2)+' м²').join('; ')+(r.overlap_pairs_truncated?' · список сокращён':'')+'</p>':''}${jointSchemePreview(d)}</details>`;
}
function unreadableInfo(d){return (d.unreadable_tables||[]).map(t=>'<p>Не прочитана таблица '+escapeHtml(t.label)+' · стр. '+t.heading_page+': '+t.issues.map(x=>escapeHtml(x.reason)).join('; ')+'</p>').join('');}
function schemePreview(t){
 if(!t.outline_xy)return '';
 const pts=t.outline_xy,xs=pts.map(p=>p[0]),ys=pts.map(p=>p[1]);
 const loX=Math.min(...xs),hiX=Math.max(...xs),loY=Math.min(...ys),hiY=Math.max(...ys),scale=300/Math.max(hiX-loX,hiY-loY,1);
 const offsetX=(360-(hiX-loX)*scale)/2,offsetY=(360-(hiY-loY)*scale)/2;
 const points=pts.map(p=>`${offsetX+(p[0]-loX)*scale},${360-offsetY-(p[1]-loY)*scale}`).join(' ');
 return `<svg viewBox="0 0 360 360" style="width:360px;max-width:100%;background:#f2f5ef" role="img" aria-label="Контур ${escapeHtml(t.label)} в координатах таблицы"><polygon points="${points}" fill="#d5e4d3" stroke="#315c46" stroke-width="2"/><text x="12" y="20" fill="#315c46">Y ↑ · X →</text><text x="12" y="344" fill="#315c46">Контур в X/Y · геопривязки нет</text></svg>`;
}
async function refreshSchemes(){
 const {result:r,attempt:a,current_catalog_id:c,remaining:n}=await api('/api/schemes');currentSchemes=r;
 if(!r){el('scheme-status').textContent=a?.error||'Таблицы ещё не извлекались.';return;}
 const tables=r.documents.flatMap(d=>d.tables||[]),errors=r.documents.filter(d=>d.state==='error').length;
 el('scheme-status').textContent=`Документов обработано: ${r.documents.length}; таблиц: ${tables.length}; контуров для сверки: ${tables.filter(t=>t.state==='review_required').length}; ошибок файлов: ${errors}; в очереди: ${n}.\n${r.warning}${r.catalog_id!==c?'\nКаталог изменился; запустите следующую порцию для актуализации.':''}${a?.state==='running'?'\nОбработка порции: '+a.processed+' / '+a.requested:''}${a?.state==='error'?'\nНе завершено: '+a.error:''}${a?.state==='interrupted'?'\nПоследняя попытка прервана.':''}`;
 el('scheme-export').classList.remove('hidden');
 el('scheme-results').innerHTML=r.documents.filter(d=>d.tables?.length||d.unparsed_coordinate_pages?.length||d.unreadable_tables?.length||d.state==='error').map(d=>`<details><summary>${escapeHtml(d.title)} · таблиц: ${d.tables?.length||0}</summary><p><a href="${escapeHtml(d.url)}" target="_blank" rel="noopener noreferrer">Официальный PDF</a><br>PDF получен: ${escapeHtml(d.source_received_at)}<br>Таблицы извлечены: ${escapeHtml(d.processed_at)}</p>${d.state==='error'?'<p>'+escapeHtml(d.error)+'</p>':`<p>Текст: ${d.processed_pages} из ${d.total_pages} страниц; сканы: ${escapeHtml((d.image_or_sparse_pages||[]).join(', ')||'нет отмеченных')}. Сканы не используются для автоматического извлечения координат.</p><p>Указания СК: ${d.crs_mentions?.map(x=>escapeHtml(x.label)+' (стр. '+x.page+')').join('; ')||'не найдены'}. Параметры преобразования не подтверждены.</p>${d.unparsed_coordinate_pages?.length?'<p>Числовые пары вне поддержанного формата: страницы '+escapeHtml(d.unparsed_coordinate_pages.join(', '))+'. Требуют отдельного чтения.</p>':''}`}${jointSchemeReview(d)}${unreadableInfo(d)}${d.content_conflicts?.length||d.listing_conflict?'<p><b>Конфликт заголовков источника. Применимость документа требует сверки.</b></p>':''}${(d.tables||[]).map(t=>`<details><summary>${escapeHtml(t.label)} · стр. ${escapeHtml(t.pages.join(', '))} · ${t.state==='rejected'?'контур отклонён':Number(t.local_area_m2).toLocaleString('ru-RU')+' м² по таблице'}</summary><p>${schemePurpose[t.purpose_hint]||'Назначение не определено'} · контекст: стр. ${t.context_page}. Это признак текста, а не правовая классификация.<br>${t.closure==='explicit'?'Замыкающая точка есть в таблице.':'Для предпросмотра последняя вершина соединена с первой; полноту кольца нужно сверить.'}</p>${t.issues.map(x=>'<p>'+escapeHtml(x.reason)+(x.page?' · стр. '+x.page:'')+(x.row?'<br>'+escapeHtml(x.row):'')+'</p>').join('')}${schemePreview(t)}<p>Оси соответствуют столбцам таблицы. Север и положение на местности не установлены. Площадь вычислена по исходным координатам, не подтверждает площадь или доступность участка.</p><details><summary>Исходные строки точек: ${t.points.length}</summary><table><thead><tr><th>Точка</th><th>X</th><th>Y</th><th>Страница</th></tr></thead><tbody>${t.points.map(p=>`<tr><td>${escapeHtml(p.label)}</td><td>${p.x}</td><td>${p.y}</td><td>${p.page}</td></tr>`).join('')}</tbody></table></details></details>`).join('')}</details>`).join('')||'<p>Поддержанные таблицы не найдены. Это не отсутствие схем или координат в документах.</p>';
 if(typeof refreshGeoreference==='function')await refreshGeoreference();
}
async function runSchemes(){
 if(running)return;running=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);
 try{
  const c=await api('/api/municipal');
  const j=await api('/api/schemes',{catalog_id:c.result?.id,retry_errors:el('scheme-retry').checked});let s;
  do{await new Promise(r=>setTimeout(r,1000));s=await api('/api/jobs/'+j.job_id);await refreshSchemes()}while(s.state==='running');
  if(s.state==='error')throw Error(s.error);
 }catch(e){el('scheme-status').textContent+='\nНе завершено: '+e.message}
 finally{running=false;document.querySelectorAll('button').forEach(b=>b.disabled=false)}
}
el('scheme-run').addEventListener('click',runSchemes);
refreshSchemes().catch(e=>el('scheme-status').textContent=e.message);
