const catalogueKinds={project_territory:'Граница территории проекта',formed_context:'Образуемые участки — по заголовку',public_use_context:'Общее назначение — по заголовку',other_land_user_context:'Посторонний землепользователь, электросетевое хозяйство — по заголовку'};
function catalogueIssues(items){return items.map(x=>'<p>'+escapeHtml(x.reason)+(x.page?' · стр. '+x.page:'')+(x.row?'<br>'+escapeHtml(x.row):'')+'</p>').join('');}
function cataloguePreview(r){
 if(!r.outline_columns)return '';
 const pts=r.outline_columns,x=Math.min(...pts.map(p=>p[0])),y=Math.min(...pts.map(p=>p[1])),dx=Math.max(...pts.map(p=>p[0]))-x,dy=Math.max(...pts.map(p=>p[1]))-y,scale=290/Math.max(dx,dy,1),ox=(360-dx*scale)/2,oy=(360-dy*scale)/2;
 const points=pts.map(p=>`${ox+(p[0]-x)*scale},${360-oy-(p[1]-y)*scale}`).join(' ');
 return `<svg viewBox="0 0 360 360" style="width:360px;max-width:100%;background:#f2f5ef" role="img" aria-label="Кольцо каталога в исходных столбцах"><polygon points="${points}" fill="#e9d9b7" stroke="#756041" stroke-width="2"/><text x="12" y="20">Столбец 2 ↑ · столбец 1 →</text><text x="12" y="344">Исходные числа · геопривязки нет</text></svg>`;
}
function catalogueAreas(items){return items.map(a=>`<p>В источнике указано: ${schemeNumber(a.stated_area_m2)} м² · стр. ${a.page}${a.scope==='all_catalogue_contours'?' · для всех контуров этого каталога':''}.<br>${a.source_rows.map(escapeHtml).join('<br>')}</p>`).join('');}
function coordinateCatalogs(d){
 const errors=d.coordinate_catalog_error?'<p>Разбор расположения каталогов не завершён: '+escapeHtml(d.coordinate_catalog_error)+'</p>':'';
 return errors+(d.coordinate_catalogs||[]).map(c=>`<details class="coordinate-catalog"><summary>Каталог ${escapeHtml(c.section)} · ${c.phase?'этап межевания '+c.phase:'граница территории'} · обозначений: ${c.parts.length}</summary>
 <p>${escapeHtml(c.source_heading)} · стр. ${c.heading_page}</p><p>${escapeHtml(c.warning)}</p><p>${catalogueKinds[c.kind]||'Назначение не установлено'}. Прочитано столбцов: ${c.column_count}; обозначений для сверки: ${c.parts.filter(p=>p.state==='review_required').length}; отклонено: ${c.parts.filter(p=>p.state==='rejected').length}. Полнота не подтверждена.</p>
 <p>${c.axes_status==='explicit_xy_m'?'X/Y и метры прямо подписаны в этом каталоге; параметры системы координат не подтверждены.':'Столбцы здесь не подписаны. Оси, единицы и СК из соседнего каталога не присваиваются; площадь по координатам в м² не рассчитывается.'}</p>${catalogueAreas(c.source_areas)}${catalogueIssues(c.issues)}
 ${c.parts.map(p=>`<details><summary>${escapeHtml(p.label)} · ${p.state==='rejected'?'отклонено':'для сверки'} · колец: ${p.rings.length}</summary>${catalogueAreas(p.source_areas)}${catalogueIssues(p.issues)}
 ${p.rings.map((r,i)=>`<details><summary>Кольцо ${i+1} · строк точек: ${r.points.length} · ${r.state==='rejected'?'отклонено':'для сверки'}</summary><p>${r.closure==='explicit'?'Явное замыкание в источнике.':'Явного замыкания нет; кольцо не достраивается.'} Север и положение на местности не установлены.</p>${catalogueIssues(r.issues)}${r.local_area_m2!=null?'<p>По подписанным столбцам: '+schemeNumber(r.local_area_m2)+' м²; это не подтверждение площади участка.</p>':''}${cataloguePreview(r)}
 <details><summary>Исходные строки, страницы и столбцы PDF</summary><table><thead><tr><th>Точка</th><th>${c.axes_status==='explicit_xy_m'?'X, м':'Столбец 1'}</th><th>${c.axes_status==='explicit_xy_m'?'Y, м':'Столбец 2'}</th><th>Стр. / столбец PDF</th><th>Исходная строка</th></tr></thead><tbody>${r.points.map(x=>`<tr><td>${escapeHtml(x.label)}</td><td>${x.column_1}</td><td>${x.column_2}</td><td>${x.page} / ${x.column}</td><td>${escapeHtml(x.source_row)}</td></tr>`).join('')}</tbody></table></details></details>`).join('')}</details>`).join('')}</details>`).join('');
}
